---
services:
  docker-code-server:
    image: gabemendoza1/docker-code-server:jammy22.04-python3.10-codeserver-v${CODE_RELEASE:-4.102.1}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - VERSION=${VERSION:-4.102.1}
        - CODE_RELEASE=${CODE_RELEASE:-4.102.1}
    environment:
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}
      - TZ=${TZ:-America/Chicago}
      - PROXY_DOMAIN=${PROXY_DOMAIN:-}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE:-/workspace}
      - PWA_APPNAME=${PWA_APPNAME:-code-server}
    ports:
      - "${HOST_PORT:-8443}:8443"
